import 'package:modif_mobil/model/cars_tipe.dart';

class CarsData {
  final List<CarTipe> carsData = [
    CarTipe(
        nameCars: 'BMW E46 M3 CSL',
        priceCars: '10.000.000.000',
        imageAssets: 'images/2.jpg',
        yearsCars: '2004',
        merkCars: 'BMW',
        tipeCars: 'E46 M3 CSL',
        tranmisitionCars: 'Manual',
        engineCars: '3000',
        drivetrainCars: 'RWD',
        kmCars: '10.000',
        conditionCars: 'Bekas',
        colorCars: 'Abu-Abu',
        doorCars: '3',
        capacityCars: '2+2',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '8',
        hpCars: '350',
        lincenseCars: 'Genap'
    ),
    CarTipe(
        nameCars: "Honda Civic Type R",
        imageAssets: "images/3.jpg",
        priceCars: "900.000.000",
        yearsCars: '2015',
        merkCars: 'Honda',
        tipeCars: 'Type R FK 2',
        tranmisitionCars: 'Manual',
        engineCars: '1996',
        drivetrainCars: 'FWD',
        kmCars: '2.000',
        conditionCars: 'Bekas',
        colorCars: 'Biru',
        doorCars: '5',
        capacityCars: '2+3',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '4',
        hpCars: '306',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "Mistubishi Lancer Evolution VI",
        imageAssets: "images/4.jpg",
        priceCars: "800.000.000",
        yearsCars: '2000',
        merkCars: 'Mitsubishi',
        tipeCars: 'GSR',
        tranmisitionCars: 'Manual',
        engineCars: '1997',
        drivetrainCars: 'AWD',
        kmCars: '30.000',
        conditionCars: 'Bekas',
        colorCars: 'Merah',
        doorCars: '5',
        capacityCars: '2+3',
        gasolineCars: 'Bensin Ron 92',
        silindersCars: '4',
        hpCars: '276',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "BMW Alphina M3 E30",
        imageAssets: "images/bmwm3alpina.jpg",
        priceCars: "3.000.000.000",
        yearsCars: '1988',
        merkCars: 'BMW',
        tipeCars: 'E30 M3',
        tranmisitionCars: 'Manual',
        engineCars: '3000',
        drivetrainCars: 'AWD',
        kmCars: '10.000',
        conditionCars: 'Bekas',
        colorCars: 'Hijau Tua',
        doorCars: '3',
        capacityCars: '2',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '6',
        hpCars: '254',
        lincenseCars: 'Genap'),
    CarTipe(
        nameCars: "Toyota Kijang Innova",
        imageAssets: "images/whiteinnova.jpg",
        priceCars: "120.000.000",
        yearsCars: '2015',
        merkCars: 'Toyota',
        tipeCars: 'Grand Kijang Innova',
        tranmisitionCars: 'Manual',
        engineCars: '2000',
        drivetrainCars: 'RWD',
        kmCars: '70.000',
        conditionCars: 'Bekas',
        colorCars: 'Putih',
        doorCars: '5',
        capacityCars: '2 + 3 + 2',
        gasolineCars: 'Bensin Ron 92',
        silindersCars: '4',
        hpCars: '123',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "Mitshubishi Pajero Sport",
        imageAssets: "images/pajero.jpg",
        priceCars: "330.000.000",
        yearsCars: '2017',
        merkCars: 'Mitshubishi',
        tipeCars: 'Pajero Sport',
        tranmisitionCars: 'CVT',
        engineCars: '2500',
        drivetrainCars: 'AWD',
        kmCars: '30.000',
        conditionCars: 'Bekas',
        colorCars: 'Putih',
        doorCars: '5',
        capacityCars: '2 + 3 + 2',
        gasolineCars: 'Diesel',
        silindersCars: '6',
        hpCars: '173',
        lincenseCars: 'Genap'),
    CarTipe(
        nameCars: 'Toyota 86',
        priceCars: '720.000.000',
        imageAssets: 'images/86.jpg',
        yearsCars: '2017',
        merkCars: 'Toyota',
        tipeCars: '86',
        tranmisitionCars: 'CVT',
        engineCars: '2000',
        drivetrainCars: 'FWD',
        kmCars: '20.000',
        conditionCars: 'Bekas',
        colorCars: 'Biru',
        doorCars: '3',
        capacityCars: '2+2',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '4',
        hpCars: '150',
        lincenseCars: 'Genap'
    ),
    CarTipe(
        nameCars: "Mitshubishi Lancer Evolution IX Wagon",
        imageAssets: "images/evowagon.jpg",
        priceCars: "1.200.000.000",
        yearsCars: '2005',
        merkCars: 'Mitshubishi',
        tipeCars: 'Lancer Evolution Wagon',
        tranmisitionCars: 'Manual',
        engineCars: '2500',
        drivetrainCars: 'AWD',
        kmCars: '20.000',
        conditionCars: 'Bekas',
        colorCars: 'Silver',
        doorCars: '5',
        capacityCars: '2+3+2',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '4',
        hpCars: '270',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "Nissan GTR E35",
        imageAssets: "images/gtre35.jpg",
        priceCars: "2.800.000.000",
        yearsCars: '2015',
        merkCars: 'Nissan',
        tipeCars: 'GTR E35',
        tranmisitionCars: 'CVT',
        engineCars: '4000',
        drivetrainCars: 'AWD',
        kmCars: '21.000',
        conditionCars: 'Bekas',
        colorCars: 'Merah',
        doorCars: '2',
        capacityCars: '2',
        gasolineCars: 'Bensin Ron 98',
        silindersCars: '8',
        hpCars: '676',
        lincenseCars: 'Genap'),
    CarTipe(
        nameCars: "Nissan Skyline GTR E34 Liberty Walk",
        imageAssets: "images/lbgtre34.jpg",
        priceCars: "2.800.000.000",
        yearsCars: '1999',
        merkCars: 'Nissan',
        tipeCars: 'Skyline GTR E34',
        tranmisitionCars: 'Manual',
        engineCars: '3000',
        drivetrainCars: 'AWD',
        kmCars: '10.000',
        conditionCars: 'Bekas',
        colorCars: 'Merah',
        doorCars: '3',
        capacityCars: '2',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '6',
        hpCars: '274',
        lincenseCars: 'Genap'),
    CarTipe(
        nameCars: "Toyota Supra MK5",
        imageAssets: "images/supramk5.jpg",
        priceCars: "2.020.000.000",
        yearsCars: '2019',
        merkCars: 'Toyota',
        tipeCars: 'Supra MK5',
        tranmisitionCars: 'Manual',
        engineCars: '3000',
        drivetrainCars: 'RWD',
        kmCars: '2.000',
        conditionCars: 'Bekas',
        colorCars: 'Putih',
        doorCars: '2',
        capacityCars: '2 ',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '6',
        hpCars: '410',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "Subaru Impreza WRX STI",
        imageAssets: "images/wrx.jpg",
        priceCars: "500.000.000",
        yearsCars: '2015',
        merkCars: 'Subaru',
        tipeCars: 'WRX STI',
        tranmisitionCars: 'Manual',
        engineCars: '2000',
        drivetrainCars: 'RWD',
        kmCars: '20.000',
        conditionCars: 'Bekas',
        colorCars: 'Blue',
        doorCars: '4',
        capacityCars: '2 + 3 ',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '4',
        hpCars: '172',
        lincenseCars: 'Ganjil'),
    CarTipe(
        nameCars: "Toyota Yaris GR",
        imageAssets: "images/yaris.jpg",
        priceCars: "1.200.000.000",
        yearsCars: '2020',
        merkCars: 'Toyota',
        tipeCars: 'Yaris GR',
        tranmisitionCars: 'Manual',
        engineCars: '700',
        drivetrainCars: 'FWD',
        kmCars: '70.000',
        conditionCars: 'Bekas',
        colorCars: 'Hitam',
        doorCars: '4',
        capacityCars: '2 + 3 ',
        gasolineCars: 'Bensin Ron 95',
        silindersCars: '4',
        hpCars: '257',
        lincenseCars: 'Genap'),

  ];
}
